# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from forthic.grpc import forthic_runtime_pb2 as forthic__runtime__pb2

GRPC_GENERATED_VERSION = '1.75.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in forthic_runtime_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ForthicRuntimeStub(object):
    """Service for executing Forthic words across runtime boundaries
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ExecuteWord = channel.unary_unary(
                '/forthic.ForthicRuntime/ExecuteWord',
                request_serializer=forthic__runtime__pb2.ExecuteWordRequest.SerializeToString,
                response_deserializer=forthic__runtime__pb2.ExecuteWordResponse.FromString,
                _registered_method=True)
        self.ExecuteSequence = channel.unary_unary(
                '/forthic.ForthicRuntime/ExecuteSequence',
                request_serializer=forthic__runtime__pb2.ExecuteSequenceRequest.SerializeToString,
                response_deserializer=forthic__runtime__pb2.ExecuteSequenceResponse.FromString,
                _registered_method=True)
        self.ListModules = channel.unary_unary(
                '/forthic.ForthicRuntime/ListModules',
                request_serializer=forthic__runtime__pb2.ListModulesRequest.SerializeToString,
                response_deserializer=forthic__runtime__pb2.ListModulesResponse.FromString,
                _registered_method=True)
        self.GetModuleInfo = channel.unary_unary(
                '/forthic.ForthicRuntime/GetModuleInfo',
                request_serializer=forthic__runtime__pb2.GetModuleInfoRequest.SerializeToString,
                response_deserializer=forthic__runtime__pb2.GetModuleInfoResponse.FromString,
                _registered_method=True)


class ForthicRuntimeServicer(object):
    """Service for executing Forthic words across runtime boundaries
    """

    def ExecuteWord(self, request, context):
        """Execute a single word in the remote runtime
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecuteSequence(self, request, context):
        """Execute a sequence of words in one remote call (batched execution optimization)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListModules(self, request, context):
        """Phase 3: Module discovery
        List available runtime-specific modules (excludes standard library)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetModuleInfo(self, request, context):
        """Get detailed information about a specific module
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ForthicRuntimeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ExecuteWord': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteWord,
                    request_deserializer=forthic__runtime__pb2.ExecuteWordRequest.FromString,
                    response_serializer=forthic__runtime__pb2.ExecuteWordResponse.SerializeToString,
            ),
            'ExecuteSequence': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteSequence,
                    request_deserializer=forthic__runtime__pb2.ExecuteSequenceRequest.FromString,
                    response_serializer=forthic__runtime__pb2.ExecuteSequenceResponse.SerializeToString,
            ),
            'ListModules': grpc.unary_unary_rpc_method_handler(
                    servicer.ListModules,
                    request_deserializer=forthic__runtime__pb2.ListModulesRequest.FromString,
                    response_serializer=forthic__runtime__pb2.ListModulesResponse.SerializeToString,
            ),
            'GetModuleInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetModuleInfo,
                    request_deserializer=forthic__runtime__pb2.GetModuleInfoRequest.FromString,
                    response_serializer=forthic__runtime__pb2.GetModuleInfoResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'forthic.ForthicRuntime', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('forthic.ForthicRuntime', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ForthicRuntime(object):
    """Service for executing Forthic words across runtime boundaries
    """

    @staticmethod
    def ExecuteWord(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/forthic.ForthicRuntime/ExecuteWord',
            forthic__runtime__pb2.ExecuteWordRequest.SerializeToString,
            forthic__runtime__pb2.ExecuteWordResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExecuteSequence(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/forthic.ForthicRuntime/ExecuteSequence',
            forthic__runtime__pb2.ExecuteSequenceRequest.SerializeToString,
            forthic__runtime__pb2.ExecuteSequenceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListModules(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/forthic.ForthicRuntime/ListModules',
            forthic__runtime__pb2.ListModulesRequest.SerializeToString,
            forthic__runtime__pb2.ListModulesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetModuleInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/forthic.ForthicRuntime/GetModuleInfo',
            forthic__runtime__pb2.GetModuleInfoRequest.SerializeToString,
            forthic__runtime__pb2.GetModuleInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
